server:
  port: ${SERVER_PORT}
spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION_MS}
  # cloud:
  #   gateway:
  #     routes:
  #       - id:
  #         uri: lb://user-service
  #         predicates:
  #           - Path=/api/v1/auth/**
  #       - id: user-service
  #         uri: lb://user-service
  #         predicates:
  #           - Path=/api/v1/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
