server:
  port: ${SERVER_PORT}
spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION_MS}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - https://talentradar-frontend-project-rw.vercel.app
              - https://talentradar-frontend-proj-git-ee52f0-muhirwas-projects-2023eaf6.vercel.app
              
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/roles/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/admin/sessions/**
        # assessment Service Routes
        - id: assessment-service
          uri: lb://assessment-service
          predicates:
            - Path=/api/v1/assessments/**,/api/v1/feedbacks/**,/api/v1/dimensions/**,/api/v1/user-assign/**
        # notification Service Routes
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**,/ws-notifications/**
          filters:
            - name: RewritePath
              args:
                regexp: "/ws-notifications/(?<segment>.*)"
                replacement: "/ws-notifications/${segment}"
                
        # AI Analysis Service Routes
        - id: ai-analysis-service
          uri: lb://talentradar-ai-analysis
          predicates:
            - Path=/api/ai-analysis/**
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
