server:
  port: 8700

# Application Configuration
spring:
  application:
    name: talentradar-ai-analysis

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect property removed; Hibernate will auto-detect PostgreSQL
    # open-in-view is enabled by default; set to false to disable the warning
    # open-in-view: false

  # JWT Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:default-jwt-secret-change-me}
      expiration-ms: 86400000  # 24 hours

# Logging Configuration
logging:
  level:
    root: INFO
    com.talentradar: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
