server:
  port: ${SERVER_PORT:3000}

spring:
  data:
    redis:
      host: 3.248.193.123
      port: 6379
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  session:
    store-type: redis
    timeout: 30m

  kafka:
    bootstrap-servers: talent-radar-kafka-server-demo-hib.j.aivencloud.com:24032
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: https # 'https' is the usual value
      ssl.truststore.location: classpath:certs/truststore.jks
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
      ssl.truststore.type: JKS
      ssl.keystore.location: classpath:certs/kafka-client.p12
      ssl.keystore.password: ${KAFKA_KEYSTORE_PASSWORD}
      ssl.keystore.type: PKCS12
      ssl.key.password: ${KAFKA_KEY_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
        debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

app:
  base-url: ${APP_BASE_URL:http://localhost:4200}
  notification:
    email:
      from: ${APP_NOTIFICATION_EMAIL_FROM}
      subject:
        prefix: ${APP_NOTIFICATION_EMAIL_SUBJECT_PREFIX}
  registration:
    token:
      secret: ${APP_REGISTRATION_TOKEN_SECRET}
      expiration-ms: ${APP_REGISTRATION_TOKEN_EXPIRATION_MS:86400000}

topic:
  user-created: user-created
  user-updated: user-updated
